main: net.icelane.massband.Plugin

name: Massband
version: 3.0.7 beta
description: Various measuring tools for making the players building life a bit easier.
author: MrX13415
website: https://dev.bukkit.org/bukkit-plugins/massband/

commands:
  massband:
    aliases: [mb]
    description: Manage Massband
    permission: massband.command      
    usage: |
           /<self> [command]

permissions:
  massband.*:
     description: Gives access to all Massband functions.
     children:
       massband.command: true
       
       
  massband.interact:
     description: Gives access to the settings command.
     default: false 
     
  massband.command:
     description: Root permission of the Massband command
     default: true
     children:
         massband.command.settings: true
         
  massband.command.count:
     description: Gives access to the settings command.
  massband.command.default:
     description: Gives access to the settings command.
  massband.command.info:
     description: Gives access to the settings command.
  massband.command.mode:
     description: Gives access to the settings command.
  
  massband.command.settings:
     description: Gives access to the settings command.
  massband.command.settings.other:
     description: Gives access to the settings command.
  massband.command.settings.config:
     description: Gives access to the settings command.
  massband.command.settings.default:
     description: Gives access to the settings command.
  
  massband.debug:
     description: Gives access to the debug command.
  massband.debug.matrix:
     description: Gives access to the debug command.
  massband.debug.message:
     description: Gives access to the debug command.
  massband.debug.ownertags:
     description: Gives access to the debug command.
  massband.debug.permission:
     description: Gives access to the debug command.
