main: net.icelane.massband.Plugin

name: Massband
version: 3.0 alpha 1
description: Measuring tools for Minecraft
author: MrX13415
website: icelane.net

commands:
  massband:
    aliases: [mb]
    description: Manage Massband
    permission: massband.command
    usage: |
           /<command> [command]
