main: net.icelane.massband.Plugin

name: Massband
version: 3.0.7 beta
description: Various measuring tools for making the players building life a bit easier.
author: MrX13415
website: https://dev.bukkit.org/bukkit-plugins/massband/

commands:
  massband:
    aliases: [mb]
    description: Manage Massband
    permission: massband.command      
    usage: |
           /<command> [command]

permissions:
  massband.*:
     description: Gives access to all Massband commands
     children:
       massband.command: true
  massband.debug:
     description: Gives access to all debug commands of Massband.
  massband.command:
     description: Root permission of the Massband command
     default: true