main: net.icelane.massband.Plugin

name: Massband
version: 3.0.5 alpha
description: Various measuring tools for making the players building life a bit easier.
author: MrX13415
website: https://dev.bukkit.org/bukkit-plugins/massband/

commands:
  massband:
    aliases: [mb]
    description: Manage Massband
    permission: massband.command
    usage: |
           /<command> [command]
