main: de.MrX13415.Massband.Massband

name: Massband
version: 2.4 beta r32 (Minecraft 1.5_01)
description: Measuring-tape for Bukkit
author: MrX13415

commands:
  massband:
    aliases: mb
    description: Manages a measuring Tape
    usage: |
           Massband 2.4 - A Measuring Tape
           Right-click with a <%item> on any Block to start measuring.
            
           /massband <clear|length|switchmode>  or  /mb <clr|l|sm>
           /massband clear ------ Clears all measuring points
           /massband length ----- Returns the last measured length 
           ---------------------- (even after 'clear')
           /massband switchmode - Changes the mode between 2D and 3D 
           ---------------------- (2D - ignores differences in height)
