main: de.MrX13415.Massband.Massband

name: Massband
version: 2.5 (Minecraft 1.5_01)
description: Measuring-tape for Bukkit
author: MrX13415

commands:
  massband:
    aliases: mb
    description: Manages a measuring Tape
    usage: |
           Massband 2.5 - A Measuring Tape
           Right-click with a <%item> on any Block to start measuring.
            
           /massband             This help message
           /massband clear       Clears all measuring points
           /massband 2D          Changes the mode to 2D 
           /massband 3D          Changes the mode to 3D
           /massband lengthmode  Select the length measuring tool 
           /massband surfacemode Select the surface measuring tool
           - Length-mode ----------------------------------------
           /massband length      Returns the last measured length 
           - Surface-mode ---------------------------------------
           /massband dimensions  Returns the dimensions of the cuboid
           /massband countBlocks Returns the count of Blocks in a cuboid (exept air)           