main: de.MrX13415.Massband.Massband

name: Massband
version: 2.6.6 (MC 1.6.6)
description: Measuring-tape for Bukkit
author: MrX13415

commands:
  massband:
    aliases: mb
    description: Manages a measuring Tape
    usage: |
           Massband 2.6.6 - A Measuring Tape
           Right-click with a <%item> on any Block to start measuring.
           /massband - This help message
           /massband clear - Clears all measuring points
           /massband 2D - Changes the mode to 2D 
           /massband 3D - Changes the mode to 3D
           /massband simplemode - Select the simple measuring tool
           /massband lengthmode - Select the length measuring tool 
           /massband surfacemode - Select the surface measuring tool
           /massband stop - Interrupt Block-counting ...
           /massband stopall - Interrupts all running Block-countings
           /massband length - Returns the last measured length 
           - Surface-mode only ----------------------------------
           /massband dimensions - Returns the dimensions of the cuboid
           /massband countBlocks - Returns the count of Blocks in a cuboid (exept air)  
           /massband expand <<amount> <up|down>|vert> - expands the selection in the given direction. (vert = from bottom to the top)           